version: '3.8'
services:
  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - '8080:8080'
    depends_on:
      - redis
    volumes:
      - ./target/mydatabase-0.0.1-SNAPSHOT.jar:/app/mydatabase-0.0.1-SNAPSHOT.jar
    command: ["java", "-jar", "/app/mydatabase-0.0.1-SNAPSHOT.jar"]
